[package]
name = "wiz-launcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
futures = "0.3.28"
mini-redis = "0.4.1"
tokio = "1.32.0"
